-- Create some mock leads for testing with correct enum values
INSERT INTO leads (
  id,
  owner_id,
  title,
  description,
  category,
  budget_min,
  budget_max,
  budget_type,
  urgency,
  canton,
  zip,
  city,
  address,
  status,
  max_purchases,
  created_at
) VALUES 
(
  gen_random_uuid(),
  '72369a4d-5722-46ed-9b90-9879ebd26d7f'::uuid,
  'Küche komplett renovieren',
  'Ich möchte meine Küche komplett renovieren. Die alte Küche ist 15 Jahre alt und braucht ein Update. Ich stelle mir eine moderne, funktionale Küche vor mit neuen Geräten und Arbeitsplatten.',
  'kuechenbau'::handwerker_category,
  15000,
  25000,
  'estimate'::budget_type,
  'this_month'::urgency_level,
  'ZH'::canton,
  '8400',
  'Winterthur',
  'Musterstrasse 12',
  'active'::lead_status,
  4,
  now() - interval '2 days'
),
(
  gen_random_uuid(),
  '72369a4d-5722-46ed-9b90-9879ebd26d7f'::uuid,
  'Dach reparieren nach Sturm',
  'Nach dem letzten Sturm sind einige Ziegel lose und es gibt kleine Lecks. Brauche einen Dachdecker für eine Inspektion und Reparatur.',
  'dachdecker'::handwerker_category,
  3000,
  8000,
  'estimate'::budget_type,
  'today'::urgency_level,
  'ZH'::canton,
  '8001',
  'Zürich',
  'Bahnhofstrasse 45',
  'active'::lead_status,
  3,
  now() - interval '1 day'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  'Garten neu gestalten',
  'Möchte meinen Garten komplett neu gestalten. Neue Terrasse, Bepflanzung und eventuell einen kleinen Teich.',
  'gartenbau'::handwerker_category,
  10000,
  20000,
  'estimate'::budget_type,
  'planning'::urgency_level,
  'ZH'::canton,
  '8050',
  'Zürich',
  'Seestrasse 78',
  'active'::lead_status,
  4,
  now() - interval '3 hours'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  'Elektroinstallation Neubau',
  'Neubau eines Einfamilienhauses. Brauche einen Elektriker für die komplette Elektroinstallation.',
  'elektriker'::handwerker_category,
  12000,
  18000,
  'estimate'::budget_type,
  'this_month'::urgency_level,
  'AG'::canton,
  '5000',
  'Aarau',
  'Hauptstrasse 22',
  'active'::lead_status,
  3,
  now() - interval '5 hours'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  'Heizung modernisieren',
  'Alte Ölheizung soll durch eine moderne Wärmepumpe ersetzt werden. Haus hat 150m² Wohnfläche.',
  'heizung'::handwerker_category,
  20000,
  35000,
  'estimate'::budget_type,
  'planning'::urgency_level,
  'ZH'::canton,
  '8404',
  'Winterthur',
  'Technikumstrasse 5',
  'active'::lead_status,
  4,
  now() - interval '1 hour'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  'Badezimmer sanieren',
  'Komplette Badrenovierung: neue Fliesen, Sanitäranlagen und moderne Armaturen. Bad ist ca. 8m².',
  'badumbau'::handwerker_category,
  8000,
  15000,
  'estimate'::budget_type,
  'this_week'::urgency_level,
  'BE'::canton,
  '3000',
  'Bern',
  'Kornhausplatz 8',
  'active'::lead_status,
  4,
  now() - interval '6 hours'
);